sudo: required
language: node_js
notifications:
  email: www.rafadraw@gmail.com
node_js:
  - 13.7.0
services:
  - postgresql
env:
  global:
    - NODE_ENV: test
    - TRAVIS: true
addons:
  postgresql: '12.1'
